# Generated by Django 3.1.2 on 2020-10-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rumble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='0.0.0.0/0', max_length=200)),
                ('port', models.IntegerField(default=80)),
            ],
        ),
    ]
