# Generated by Django 3.1.2 on 2020-10-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_tut', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rumble',
            name='addresses',
            field=models.CharField(default='0.0.0.0/0', max_length=200),
        ),
        migrations.AddField(
            model_name='rumble',
            name='addresses_extra',
            field=models.CharField(default='0.0.0.0/0', max_length=200),
        ),
        migrations.AddField(
            model_name='rumble',
            name='alive',
            field=models.CharField(default=False, max_length=25),
        ),
    ]
